# Dependencies and Data

In [1]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df = pd.read_csv(os.path.join('../../Experiments/TensorflowCommentToxicity/data','train.csv', 'train.csv'))

In [3]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [4]:
df[df['toxic'] == 1].head(
)

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [5]:
df.iloc[16]["comment_text"]

"Bye! \n\nDon't look, come or think of comming back! Tosser."

In [6]:
df[df.columns[2:]].iloc[16]

toxic            1
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 16, dtype: int64

# Pre Processing

In [7]:
!pip list

Package                      Version
---------------------------- ------------
absl-py                      1.4.0
aiohttp                      3.8.5
aiosignal                    1.3.1
annotated-types              0.5.0
anyio                        4.0.0
argon2-cffi                  23.1.0
argon2-cffi-bindings         21.2.0
arrow                        1.2.3
asttokens                    2.4.0
astunparse                   1.6.3
async-lru                    2.0.4
async-timeout                4.0.3
attrs                        23.1.0
Automat                      22.10.0
Babel                        2.12.1
backcall                     0.2.0
beautifulsoup4               4.12.2
bleach                       6.0.0
blis                         0.7.11
cachetools                   5.3.2
catalogue                    2.0.10
certifi                      2023.7.22
cffi                         1.15.1
charset-normalizer           3.2.0
chex                         0.1.85
click                        8.

In [8]:
from tensorflow.keras.layers import TextVectorization

In [9]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [10]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [11]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [12]:
MAX_FEATURES = 200000 # number of words in the vocab

In [13]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                              output_sequence_length=1800,
                              output_mode='int')

In [14]:
type(X)

pandas.core.series.Series

In [15]:
type(X.values)

numpy.ndarray

In [16]:
vectorizer.adapt(X.values)

In [17]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [18]:
vectorizer("Hello my name is anacleto")[:5].numpy()

array([288,  29, 109,   9,   1], dtype=int64)

In [19]:
vectorized_text = vectorizer(X.values)

In [20]:
len(X)

159571

In [21]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

MCSHBAP - map, chache, shuffle, batch, prefetch  from_tensor_slices, list_file

In [22]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))

In [23]:
dataset = dataset.cache()

In [24]:
dataset = dataset.shuffle(160000)

In [25]:
dataset = dataset.batch(16)

In [26]:
dataset = dataset.prefetch(8) # helps bottlenecks

In [27]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

# Creating a Sequential Model

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [29]:
model = Sequential()

In [30]:
# Create the embedding layer
model.add(Embedding(input_dim=MAX_FEATURES+1, output_dim=32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layer
model.add(Dense(6, activation='sigmoid'))

In [31]:


model.compile(loss='BinaryCrossentropy', optimizer='Adam')



In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [33]:
history = model.fit(train, epochs=5, validation_data=val)

Epoch 1/5
6981/6981 [==============================] - 2870s 410ms/step - loss: 0.0646 - val_loss: 0.0470
Epoch 2/5
6981/6981 [==============================] - 2797s 401ms/step - loss: 0.0455 - val_loss: 0.0423
Epoch 3/5
6981/6981 [==============================] - 2805s 402ms/step - loss: 0.0412 - val_loss: 0.0383
Epoch 4/5
6981/6981 [==============================] - 2881s 413ms/step - loss: 0.0374 - val_loss: 0.0331
Epoch 5/5
6981/6981 [==============================] - 2814s 403ms/step - loss: 0.0339 - val_loss: 0.0296


In [34]:
history.history

{'loss': [0.064572773873806,
  0.045497145503759384,
  0.04117614030838013,
  0.03741911053657532,
  0.03387762978672981],
 'val_loss': [0.04698442295193672,
  0.0422605536878109,
  0.03831275925040245,
  0.03311794996261597,
  0.02960280328989029]}

# Make predictions

In [36]:
input_text = vectorizer('You freaking suck! I am going to hit you.')

In [37]:
input_text

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([   7, 7158,  397, ...,    0,    0,    0], dtype=int64)>

In [38]:
model.predict(np.array([input_text]))

1/1 [==============================] - 1s 880ms/step


array([[0.99955636, 0.35582623, 0.9870527 , 0.09045257, 0.94556886,
        0.1805285 ]], dtype=float32)

In [39]:
 model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 63ms/step


array([[0.99955636, 0.35582623, 0.9870527 , 0.09045257, 0.94556886,
        0.1805285 ]], dtype=float32)

In [40]:
res = model.predict(np.expand_dims(input_text,0))
res

1/1 [==============================] - 0s 62ms/step


array([[0.99955636, 0.35582623, 0.9870527 , 0.09045257, 0.94556886,
        0.1805285 ]], dtype=float32)

In [41]:
test.as_numpy_iterator().next()

(array([[   29,  1376,    94, ...,     0,     0,     0],
        [  257,   850,   844, ...,     0,     0,     0],
        [  425,   597,    40, ...,     0,     0,     0],
        ...,
        [51119,    82,   470, ...,     0,     0,     0],
        [  382,   762,   397, ...,     0,     0,     0],
        [ 1397, 23183,    25, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [42]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [43]:
# Predicted results from batch X
(model.predict(batch_X) > 0.5).astype(int)

1/1 [==============================] - 0s 70ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
# Labels from batch_X
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [45]:
res.shape

(1, 6)

In [46]:
res = model.predict(batch_X)
res

1/1 [==============================] - 0s 69ms/step


array([[2.64072551e-05, 2.11575619e-23, 3.59963423e-07, 1.63733721e-10,
        6.33534569e-07, 4.58630106e-10],
       [1.32312078e-03, 3.83021988e-15, 5.30669822e-05, 4.48770550e-07,
        7.82104617e-05, 7.76130776e-07],
       [9.99723136e-01, 1.85685530e-01, 9.97995496e-01, 5.52891567e-03,
        8.78637791e-01, 1.30231138e-02],
       [1.50466501e-03, 1.05899075e-14, 4.43439894e-05, 6.37695280e-07,
        7.43091587e-05, 8.98351232e-07],
       [3.85061248e-05, 1.38694950e-22, 6.16239731e-07, 4.67236250e-10,
        1.13031820e-06, 9.38685241e-10],
       [1.65843219e-03, 6.17457948e-14, 2.26286757e-05, 9.36722756e-07,
        4.87015277e-05, 9.48909531e-07],
       [9.73859301e-07, 1.87793479e-30, 4.34112346e-09, 1.76864261e-13,
        8.52129123e-09, 6.53040935e-13],
       [3.34778684e-04, 1.52624799e-17, 5.92299102e-06, 4.80097384e-08,
        1.13046563e-05, 5.31755973e-08],
       [5.01950635e-05, 7.42480074e-22, 7.25365851e-07, 8.61676785e-10,
        1.39363067e-06, 

In [47]:
res.shape

(16, 6)

In [48]:
res.flatten()

array([2.64072551e-05, 2.11575619e-23, 3.59963423e-07, 1.63733721e-10,
       6.33534569e-07, 4.58630106e-10, 1.32312078e-03, 3.83021988e-15,
       5.30669822e-05, 4.48770550e-07, 7.82104617e-05, 7.76130776e-07,
       9.99723136e-01, 1.85685530e-01, 9.97995496e-01, 5.52891567e-03,
       8.78637791e-01, 1.30231138e-02, 1.50466501e-03, 1.05899075e-14,
       4.43439894e-05, 6.37695280e-07, 7.43091587e-05, 8.98351232e-07,
       3.85061248e-05, 1.38694950e-22, 6.16239731e-07, 4.67236250e-10,
       1.13031820e-06, 9.38685241e-10, 1.65843219e-03, 6.17457948e-14,
       2.26286757e-05, 9.36722756e-07, 4.87015277e-05, 9.48909531e-07,
       9.73859301e-07, 1.87793479e-30, 4.34112346e-09, 1.76864261e-13,
       8.52129123e-09, 6.53040935e-13, 3.34778684e-04, 1.52624799e-17,
       5.92299102e-06, 4.80097384e-08, 1.13046563e-05, 5.31755973e-08,
       5.01950635e-05, 7.42480074e-22, 7.25365851e-07, 8.61676785e-10,
       1.39363067e-06, 1.50648882e-09, 9.86319268e-04, 3.98483288e-16,
      

In [49]:
res.flatten().shape

(96,)

# Evaluate Model

In [50]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [51]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [52]:
for batch in test.as_numpy_iterator():
  # Unpack the batch
    X_true, y_true = batch

    # Make a prediction
    yhat = model.predict(X_true)

    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()

    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

1/1 [==============================] - 0s 73ms/step


In [53]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8636751174926758, Recall:0.8144081234931946, Accuracy:0.49448344111442566


# Test and Gradio

In [54]:
!pip install gradio jinja2

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/50.5 kB ? eta -:--:--
     ---------------------------------------- 50.5/50.5 kB 2.5 MB/s eta 0:00:00
     ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
     ---------------------------------------- 45.7/45.7 kB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 0.0/124.7 kB ? eta -:--:--
     -------------------------------------- 124.7/124.7 kB 3.7 MB/s eta 0:00:00
     ---------------------------------------- 0.0/58.3 kB ? eta -:--:--
     ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/16.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.6 MB 10.7 MB/s eta 0:00:02
   ----- ---------------------------------- 2.2/16.6 MB 23.0 MB/s eta 0:00:01
   --------- ------------------------------ 3.7/16.6 MB 26.5 MB

In [55]:
import gradio as gr

C:\Users\Anacleto\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [56]:
model.save('toxicity.h5')

C:\Users\Anacleto\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [57]:
model = tf.keras.models.load_model('toxicity.h5')

In [58]:
input_str = vectorizer('hey i freaken hate you!')

In [59]:
res = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 1s/step


In [60]:
res

array([[0.80082846, 0.02024854, 0.11238011, 0.10546941, 0.419613  ,
        0.13616486]], dtype=float32)

In [61]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)

    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)

    return text



In [63]:
import gradio as gr

interface = gr.Interface(fn=score_comment,
                         inputs=gr.Textbox(lines=2, placeholder='Comment to score'),
                         outputs='text')


In [64]:
interface.launch(share=True)


Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://6e8a4dc041010fa935.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


1/1 [==============================] - 0s 66ms/step
